### ISSUE TITLE
disconnecting from server right after winning minigame

### ISSUE THREAD

**Issue by LoneWolfGmer** [TheAwesomeGem/fishing-made-better#7]
for reasons unknown each time anyone on the modded server wins the fishing minigame it disconnects us with an internal error message

far as I can tell this is the code that displays before the crash

net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NoSuchMethodError: levelup2.skills.SkillRegistry.getSkillLevel(Lnet/minecraft/entity/player/EntityPlayer;Ljava/lang/String;)I
        at net.theawesomegem.fishingmadebetter.util.LevelUpLoot.getFishingLoot(LevelUpLoot.java:42) ~[LevelUpLoot.class:?]
        at net.theawesomegem.fishingmadebetter.util.LevelUpLoot.doLevelUpLoot(LevelUpLoot.java:20) ~[LevelUpLoot.class:?]
        at net.theawesomegem.fishingmadebetter.common.event.FishingEventHandler.onPlayerFish(FishingEventHandler.java:225) ~[FishingEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1581_FishingEventHandler_onPlayerFish_ItemFishedEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraft.entity.projectile.EntityFishHook.func_146034_e(EntityFishHook.java:522) ~[acf.class:?]
        at net.theawesomegem.fishingmadebetter.common.item.fishingrod.ItemBetterFishingRod.func_77659_a(ItemBetterFishingRod.java:73) ~[ItemBetterFishingRod.class:?]
        at net.theawesomegem.fishingmadebetter.common.event.FishingEventHandler.onPlayerTick(FishingEventHandler.java:380) ~[FishingEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1578_FishingEventHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:365) ~[FMLCommonHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
        ... 9 more
[22:58:57] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: LoneWolfGmer lost connection: Internal server error

**Comment by fonnymunkey** [comment]
What version of LevelUp Reloaded is the server running? And the players?

**Comment by fonnymunkey** [comment]
If its any version newer than LevelUpReloaded 1.1.23 the server owner should set "levelUpPatch" in the config to false.

**Comment by LoneWolfGmer** [comment]
Will that fix the disconnecting issues?

**Comment by LoneWolfGmer** [comment]
Also I am the server owner. I just changed the setting you mentioned. And are having one of my players test if it works now.

**Comment by LoneWolfGmer** [comment]
Glad to report changing the config as mentioned above did fix my issue. Thanks for the help.
